### ISSUE TITLE
[M?][Low][HW] Investigate how to support SoftAP on RPI2

### ISSUE THREAD

**Issue by droneboost** [bithollow/bitforge#13]

**Comment by droneboost** [comment]
This issue has been solved.

**Comment by onceme** [comment]
I reopened this issue, because there are more things could be done on it.
Please update the wiki page in a more easy and clean way for cross referencing.
https://github.com/bithollow/docs/wiki/Enable-SoftAP-for-TL-WN725N-on-RPI

**Comment by droneboost** [comment]
I've put a wifi daemon program in https://github.com/droneboost/wifi_daemon, this program can handle SoftAP and Station mode by bit set of GPIO24, this program should be merged into rpi2.img later.

**Comment by onceme** [comment]
Would you create a deb package for install and uninstall? I can integrate such package into rpi.img.bz2

**Comment by onceme** [comment]
finished, close.
