### ISSUE TITLE
[M1][High][HW]  ALL in one  prototype(sensor hub)

### ISSUE THREAD

**Issue by muzi-15** [bithollow/bitforge#16]

**Comment by muzi-15** [comment]
Sensor:

```
MPU6050  IMU
MS5611 Barometer
U-blox M8N Glonass/GPS/Beidou
ADS1115   ADC for power monitoring
MB85RC  FRAM storage
PCA9685 PWM generator
RGB LED
Temperature Sensor - Waterproof (DS18B20)
```

**Comment by muzi-15** [comment]
```
PWM servo outputs
PPM input
PWM input
Triple redundant power supply
Power module connector
UART, SPI, I2C for extensions
HAT compliant
```

**Comment by muzi-15** [comment]
GPS SELECT:
1. http://u-blox.com/en/gps-modules/pvt-modules/neo-7.html
2. http://www.u-blox.com/en/gps-modules/pvt-modules/previous-generations/neo-6-family.html
3. http://www.u-blox.com/images/downloads/Product_Docs/GNSS-module-selector_Overview_%28UBX-14000426%29.pdf

**Comment by muzi-15** [comment]
Add the following items:
1. RTC
2. LED
3. Voltage detect
4. Buzzer
5. 5V/3/3V DC converter
6. Moderate temperature detect

**Comment by onceme** [comment]
HMC5883L

**Comment by onceme** [comment]
Now we have breadboard and BH board, consider this one closed?

**Comment by droneboost** [comment]
Since BH first edition has come out, I close this issue.
