### ISSUE TITLE
[M?][Medium][APM] Start APM automatically after RPI2 boot 

### ISSUE THREAD

**Issue by onceme** [bithollow/bitforge#19]
Start APM automatically after RPI2 boot instead of starting it through serial console or ssh shell.
- Study how to add systemd service
- Add APM service
- Consider how to connect -A telemetry, currently we are using static IP addresses

**Comment by onceme** [comment]
refer to this git, will be summarized to wiki later.
https://gist.github.com/onceme/0575eb651e8d28301bf9

**Comment by onceme** [comment]
found in field test that if the specified ip address cannot be reached, ArduCopter will not get ESC ready (the 'ready' beep sound won't fire).

My RPI2 usb wifi was set as 'dhcp', but while field testing, there was no hotspot to lease IP to RPI2. So I'm not sure whether it was because RPI2 would wait until some IP address is acquired, then start ArduCopter, or, ArduCopter was started, but it was waiting for the unreachable IP address to respond.

**Comment by droneboost** [comment]
@onceme , close this issue?

**Comment by onceme** [comment]
auto starting APM has been integrated to rpi.img.bz2
