### ISSUE TITLE
[M?][Medium][APM] Enable APM -C telemetry

### ISSUE THREAD

**Issue by onceme** [bithollow/bitforge#20]
APM should be able to connect GCS through -C telemetry, which is over serial port, but in RPI2, there is only one serial port, it is used as RPI2 serial console. Find a way to let APM use /dev/ttyAMA0 in RPI2 as -C telemetry.
- Modify cmdline.txt to disable RPI2 serial console
- Build APM with serial port /dev/ttyAMA0
- Verify it works

**Comment by onceme** [comment]
Places needs to be changed:
- $ARDUPILOT_SRC_ROOT/config.mk, "PORT = /dev/ttyAMA0"
- In RPI rootfs, /boot/firmware/cmdline.txt, remove "console=ttyAMA0,115200 kgdboc=ttyAMA0,115200"

When startup ArduCopter.elf, try the following:
$ sudo ./ArduCopter.elf -A /dev/ttyAMA0

Yes, probably you have already noticed, here we use telemetry -A instead of -C, for now -C will not work, reason unknown.

**Comment by onceme** [comment]
Found this can work:
$ sudo ./ArduCopter.elf -A /dev/ttyAMA0 -C udp:xxx.xxx.xxx.xxx:14550

By connecting serial cable and Ethernet at the same time, they work simultaneously. Either unplugging serial cable or disable Ethernet, the other one can continuously work.

-A telemetry is the default telemetry, I guess serial port should come with default. But from the actually code, I didn't find out such limitation, -A telemetry and -C telemetry could be specified as user want. Big question mark here.

**Comment by droneboost** [comment]
@onceme , close this issue?

**Comment by onceme** [comment]
Now all telemetries are enabled
