### ISSUE TITLE
[M1][High][HW] Create BH Official website

### ISSUE THREAD

**Issue by droneboost** [bithollow/bitforge#22]

**Comment by droneboost** [comment]
Onceme and D.B. will do it.

**Comment by onceme** [comment]
start from here: https://pages.github.com/

we have to decide how we generate the pages.

**Comment by onceme** [comment]
now we have the first version: https://bithollow.github.io

**Comment by droneboost** [comment]
Aaron, do you have any update for the site?

**Comment by onceme** [comment]
Not yet, hold on 2 more days

**Comment by droneboost** [comment]
Get it!

**Comment by onceme** [comment]
@droneboost Because we are going to add many pages to this site, so could you setup your local Jekyll develop environment?
- pages.github.com
- jekyllrb.com

**Comment by droneboost** [comment]
OK, I'll do it.

**Comment by onceme** [comment]
check bithollow.github.io, mark as closed.
