### ISSUE TITLE
[M?][High][HW] Collect retailer/vendor information for BOM

### ISSUE THREAD

**Issue by onceme** [bithollow/bitforge#24]
Collect parts information before we actually purchase them.
- Main parts (onceme)
- Connectors (?)
- Miscellaneous (?) 

Add retail link here.

| Parts | Pattern | Quantity | Components | Notes | Dealers links |
| --- | --- | --- | --- | --- | --- |
| PCA9685 | Quad28 | 1 | U5 | PCA9685BS | [纳达尔数码专营店](http://detail.tmall.com/item.htm?spm=a230r.1.14.42.CSOT08&id=39448841343&ns=1&abbucket=19) |
| ADS1115 | ASD1115 | 1 | U7 | ADS1115IDGSR/T | [纳达尔数码专营店](http://world.tmall.com/item/38834846102.htm?spm=a312a.7700714.0.0.wDcbjl) [单片机snq2010](http://world.taobao.com/item/13163619405.htm?spm=a312a.7700714.0.0.wDcbjl#detail) |
| UBLOX M8N | NEO-M8N | 1 | U8 | NEO-M8N-0-01 | [深圳市江东电子商行](http://item.taobao.com/item.htm?spm=a1z10.3-c.w4002-11259359514.11.UFgpft&id=42554700868) |
| MS5611 | MS5611 | 1 | U4 | MS5611-01BA | [深圳市江东电子商行](http://item.taobao.com/item.htm?spm=2013.1.w4018-11259379161.7.bC4LoF&id=14157565240&scm=1007.11837.6006.i39903117808&pvid=45149f6c-7721-4726-baab-ed235cbcbf6e) |
| MPU-6050 | MPU-6050 | 1 | U2 | MPU-6050C | [深圳市江东电子商行](http://item.taobao.com/item.htm?spm=a1z10.3-c.w4002-11259359514.23.4fWn2Q&id=35895053463) |
| HMC5883L | HMC5883L | 1 | U3 | HMC5883L-TR | [深圳市江东电子商行](http://item.taobao.com/item.htm?spm=a230r.1.14.19.NRCfpE&id=39903117808&ns=1&abbucket=19#detail) |
| MS621FE | Battery | 1 | BT2 | Battery MS621FE | [深圳市江东电子商行](http://item.taobao.com/item.htm?spm=a1z10.3-c.w4002-11259359514.9.JEwwE5&id=17111394953) |
| DS1339 | DS1339 | 1 | U6 | DS1339U-3 | [金利达微 少女show](http://world.taobao.com/item/45065635391.htm?spm=a312a.7700714.0.0.nqDQco#detail) |
| SP6205 | SP6205 | 1 | U1 | SP6205EM5 | [金利达微 少女show](http://item.taobao.com/item.htm?spm=a312a.7700824.w4002-1070494141.9.SOoWki&id=15423878212)  手头已有现货 |
| WS2812b | WS2812B | 1 | U9 | RGB Led WS2812B | [深圳鑫达电子](http://item.taobao.com/item.htm?spm=a230r.1.14.73.1mx27W&id=45488927580&ns=1&abbucket=19#detail) |
| XTAL | 32.7k | 1 | Y1 | Crystal Oscillator | [科天微数码专营店](http://world.tmall.com/item/19085262289.htm?spm=a230r.1.14.73.HC7z4m&id=19085262289&ns=1&abbucket=7) |
| Diode IN5817 | 3.5X2.8X1.9 | 1 | D3 | Diode |  |
| GPS antenna |  |  |  |  |  |
| LED1 | LED_RED | 1 | D1 | Typical RED, GREEN, YELLOW, AMBER GaAs LED | 手头已有现货 |
| LED2 | LED_ORANGE | 1 | D2 |  | 不使用 |
| LED4 | LED_BLUE | 1 | D4 |  | 手头已有现货 |
| LED5 | LED_YELLOW | 1 | D5 |  | 不使用 |
| LED6 | LED_GREEN | 1 | D6 |  | 手头已有现货 |
| 0.01uf | 1608[0603] | 1 | C8 | Capacitor |  |
| 0.1uf | 1608[0603] | 11 | C2, C5, C6, C7, C12, C13, C14, C15, C16, C17, C18 | Capacitor | 手头已有现货(但只有11个存货) |
| 0.22uf | 1608[0603] | 1 | C11 | Capacitor | 手头已有现货 |
| 2200pf | 1608[0603] | 1 | C9 | Capacitor | 手头已有现货 |
| 4.7uf | 1608[0603] | 1 | C10 | Capacitor | 手头已有现货 |
| 47uf | 1608[0603] | 1 | C1 | Capacitor |  |
| 10nf | 1608[0603] | 1 | C3 | Capacitor | 手头已有现货 |
| 10uf | 1608[0603] | 1 | C4 | Capacitor | 手头已有现货 |
| 10R | 1608[0603] | 1 | R3 | Resistor | 手头已有现货 |
| 510R | 1608[0603] | 4 | R5, R7, R8, R9 | Resistor | 手头已有现货 |
| 1K | 1608[0603] | 4 | R1, R2, R4, R6 | Resistor |  |
| 4.7K |  |  |  | Resistor | I2C上拉，原理图上遗漏，需要飞线解决 |
| 27nh | 1608[0603] | 1 | L1 | Inductance |  |
| AN | RF | 1 | J15 | Header, 5-Pin | [福强电子IC 线材](http://world.taobao.com/item/39020158549.htm?fromSite=main&spm=a230r.1.14.28.QtSNSN&ns=1&abbucket=7#detail) |
| Header 3X2 | HDR2X3 | 1 | P7 | Header, 3-Pin, Dual row |  |
| Header 6X2 | 3x4PIN | 1 | P6 | Header, 6-Pin, Dual row |  |
| I2C | 4PIN | 1 | P3 | Header, 4-Pin | [深圳市融跃电子](https://item.taobao.com/item.htm?spm=a230r.1.14.30.hFWINd&id=40377842005&ns=1&abbucket=7#detail) |
| PWM | 3X8PIN | 1 | P5 | Header, 24-Pin | [深圳嘉镁源电子元器件](https://item.taobao.com/item.htm?spm=a230r.1.14.197.WF5Rai&id=44424655846&ns=1&abbucket=7#detail) |
| RPI2 | RPI2 | 1 | P1 | Header, 20-Pin, Dual row | [骏兴源电子世界](https://item.taobao.com/item.htm?spm=a230r.1.14.42.Rphi6c&id=17681041261&ns=1&abbucket=7#detail) |
| spi | 6PIN | 1 | P2 | Header, 6-Pin | [深圳市融跃电子](https://item.taobao.com/item.htm?spm=a230r.1.14.30.hFWINd&id=40377842005&ns=1&abbucket=7#detail) |
| uart | 4PIN | 1 | P4 | Header, 4-Pin | [深圳市融跃电子](https://item.taobao.com/item.htm?spm=a230r.1.14.30.hFWINd&id=40377842005&ns=1&abbucket=7#detail) |
| CON2 | PIN2 | 1 | J1 | Connector |  |

**Comment by onceme** [comment]
# Main parts

## 纳达尔数码专营店
### PCA9685BS
http://detail.tmall.com/item.htm?spm=a230r.1.14.42.CSOT08&id=39448841343&ns=1&abbucket=19

## 深圳市江东电子商行
### NEO-M8N-0-01
http://item.taobao.com/item.htm?spm=a1z10.3-c.w4002-11259359514.11.UFgpft&id=42554700868
### MS5611-01BA
http://item.taobao.com/item.htm?spm=2013.1.w4018-11259379161.7.bC4LoF&id=14157565240&scm=1007.11837.6006.i39903117808&pvid=45149f6c-7721-4726-baab-ed235cbcbf6e
### MPU-6050C
http://item.taobao.com/item.htm?spm=a1z10.3-c.w4002-11259359514.23.4fWn2Q&id=35895053463
### HMC5883L-TR
http://item.taobao.com/item.htm?spm=a230r.1.14.19.NRCfpE&id=39903117808&ns=1&abbucket=19#detail
### MS621FE
http://item.taobao.com/item.htm?spm=a1z10.3-c.w4002-11259359514.9.JEwwE5&id=17111394953

## 金利达微 少女show
### DS1339U-3
http://world.taobao.com/item/45065635391.htm?spm=a312a.7700714.0.0.nqDQco#detail
### SP6205EM5
http://item.taobao.com/item.htm?spm=a312a.7700824.w4002-1070494141.9.SOoWki&id=15423878212

## 深圳鑫达电子
### WS2812B
http://item.taobao.com/item.htm?spm=a230r.1.14.73.1mx27W&id=45488927580&ns=1&abbucket=19#detail

**Comment by muzi-15** [comment]
Diode	3.5X2.8X1.9	1	D3( IN5817  or IN4148)

**Comment by muzi-15** [comment]
PCA9685BS 4?_10=40
ADS1115IDGSR/T 4?_13=52
NEO-M8N-0-01 4?_98=392
MS5611-01BA 4? *28=112
MPU-6050C 4?_15=60
HMC5883L-TR 4?*5=20
DS1339U-3 4?  *6=20
MS621FE MS621 4? *3=12

**Comment by droneboost** [comment]
# Total expenditure

O: Onceme,  M: Muzu-15,  D: Droneboost

| Date | Goods | Quantity | Expenditure(RMB) | Payer | Status |
| --- | --- | --- | --- | --- | --- |
| m/n? | Some e-parts for bread board + X450 center board | 1 | 49 + 17 | D to M | Paid |
| 8/10 | 1to4 + Transport fee | 10 suites | 73 | O/M/D | Paid |
| 8/10 | X450 RPI connect board | 10 suites | 50 | M/D | Paid |
| 8/3 | BH board 1st edition + Transport fee | 10 | 193 | O/M/D | Paid |
| 8/11 | PCA9685BS/ADS1115IDGSR/T/NEO-M8N-0-01/MS5611-01BA/MPU-6050C/HMC5883L-TR/DS1339U-3/MS621FE | 4 suites | 718 | O/M/D | Paid |
| 8/12 | 2.54mm 3×40pin的， 10只 X 3 = 30元 / 共阳 RGB 3528发光二极管 20 只 =5元 / 1K 电阻 0603 30只 100个2元 / 0.1uf 电容 0603封装 100只 100个3元 / 0.01uf 电容 0603封装 30只 100个3元 / 10uf 电容 0603封装 30只 100个5元 / 27nh 电感 0603封装 30只 100个4元 / 4R7 电感 5只5元 / 1.25mm间距 卧贴 4P 24 6P 12 | 10 suites | 138 - 15 | O/M/D | Paid |
| 8/12 | 40pin的排插 + Transport fee | 4 | 24 | O/M/D | Paid |
| 8/12 | GPS SMA头 + 2级管 | 2 | 33.96 | O/M/D | Paid |
| 8/12 | GPS 天线 | 2 | 58 | M/D | Paid |
| 8/19 | 贴片费用 | 3 suites | 423 | O/M/D | Paid |

**Comment by muzi-15** [comment]
2.54mm 3×40pin的， 10只 X 3 = 30元
2.54mm  2×20pin 贴片排母  5只 x1.5 = 7.5
2.54  2x20pin 贴片排针  5只 X1.5 = 7.5
共阳 RGB 3528发光二极管  20 只 =5元
1K 电阻 0603 30只  100个2元
0.1uf 电容 0603封装 100只  100个3元
0.01uf 电容 0603封装 30只  100个3元
10uf 电容 0603封装 30只  100个5元
27nh 电感 0603封装 30只   100个4元
4R7 电感  5只5元 
1.25mm间距 卧贴  4P 24 6P 12

**Comment by muzi-15** [comment]
All the elements is on their way to BH board.

**Comment by droneboost** [comment]
# Main parts

## 纳达尔数码专营店

### [PCA9685BS](http://detail.tmall.com/item.htm?spm=a230r.1.14.42.CSOT08&id=39448841343&ns=1&abbucket=19)

### [ADS1115IDGSR/T](http://world.tmall.com/item/38834846102.htm?spm=a312a.7700714.0.0.wDcbjl)

## 单片机snq2010

### [ADS1115IDGSR/T](http://world.taobao.com/item/13163619405.htm?spm=a312a.7700714.0.0.wDcbjl#detail)

## 深圳市江东电子商行

### [NEO-M8N-0-01](http://item.taobao.com/item.htm?spm=a1z10.3-c.w4002-11259359514.11.UFgpft&id=42554700868)

### [MS5611-01BA](http://item.taobao.com/item.htm?spm=2013.1.w4018-11259379161.7.bC4LoF&id=14157565240&scm=1007.11837.6006.i39903117808&pvid=45149f6c-7721-4726-baab-ed235cbcbf6e)

### [MPU-6050C](http://item.taobao.com/item.htm?spm=a1z10.3-c.w4002-11259359514.23.4fWn2Q&id=35895053463)

### [HMC5883L-TR](http://item.taobao.com/item.htm?spm=a230r.1.14.19.NRCfpE&id=39903117808&ns=1&abbucket=19#detail)

### [MS621FE](http://item.taobao.com/item.htm?spm=a1z10.3-c.w4002-11259359514.9.JEwwE5&id=17111394953)

## 金利达微 少女show

### [DS1339U-3](http://world.taobao.com/item/45065635391.htm?spm=a312a.7700714.0.0.nqDQco#detail)

### [SP6205EM5](http://item.taobao.com/item.htm?spm=a312a.7700824.w4002-1070494141.9.SOoWki&id=15423878212)

## 深圳鑫达电子

### [WS2812B](http://item.taobao.com/item.htm?spm=a230r.1.14.73.1mx27W&id=45488927580&ns=1&abbucket=19#detail)

# Connectors

# Miscellaneous

**Comment by droneboost** [comment]
# Main parts

## 纳达尔数码专营店
### [PCA9685BS](http://detail.tmall.com/item.htm?spm=a230r.1.14.42.CSOT08&id=39448841343&ns=1&abbucket=19)
### [ADS1115IDGSR/T](http://world.tmall.com/item/38834846102.htm?spm=a312a.7700714.0.0.wDcbjl)

## 单片机snq2010
### [ADS1115IDGSR/T](http://world.taobao.com/item/13163619405.htm?spm=a312a.7700714.0.0.wDcbjl#detail)

## 深圳市江东电子商行
### [NEO-M8N-0-01](http://item.taobao.com/item.htm?spm=a1z10.3-c.w4002-11259359514.11.UFgpft&id=42554700868)
### [MS5611-01BA](http://item.taobao.com/item.htm?spm=2013.1.w4018-11259379161.7.bC4LoF&id=14157565240&scm=1007.11837.6006.i39903117808&pvid=45149f6c-7721-4726-baab-ed235cbcbf6e)
### [MPU-6050C](http://item.taobao.com/item.htm?spm=a1z10.3-c.w4002-11259359514.23.4fWn2Q&id=35895053463)
### [HMC5883L-TR](http://item.taobao.com/item.htm?spm=a230r.1.14.19.NRCfpE&id=39903117808&ns=1&abbucket=19#detail)
### [MS621FE](http://item.taobao.com/item.htm?spm=a1z10.3-c.w4002-11259359514.9.JEwwE5&id=17111394953)

## 金利达微 少女show
### [DS1339U-3](http://world.taobao.com/item/45065635391.htm?spm=a312a.7700714.0.0.nqDQco#detail)
### [SP6205EM5](http://item.taobao.com/item.htm?spm=a312a.7700824.w4002-1070494141.9.SOoWki&id=15423878212)

## 深圳鑫达电子
### [WS2812B](http://item.taobao.com/item.htm?spm=a230r.1.14.73.1mx27W&id=45488927580&ns=1&abbucket=19#detail)

# Connectors 

# Miscellaneous

**Comment by droneboost** [comment]
Diode 3.5X2.8X1.9 1 D3( IN5817 or IN4148)

**Comment by droneboost** [comment]
PCA9685BS 4?10=40
ADS1115IDGSR/T 4?13=52
NEO-M8N-0-01 4?98=392
MS5611-01BA 4? _28=112
MPU-6050C 4?15=60
HMC5883L-TR 4?_5=20
DS1339U-3 4? *6=20
MS621FE MS621 4? *3=12

**Comment by droneboost** [comment]
@onceme, If this page is only for BH first edition, I'd like to close this issue.

**Comment by onceme** [comment]
Yes, it's for BH first edition, I will close it.
