### ISSUE TITLE
[M2][High][SW] Verify APM 3.3 merged by Aaron

### ISSUE THREAD

**Issue by droneboost** [bithollow/bitforge#25]
- Background
  APM3.3 has to be tested on 4.1.9 rt kernel and debian jessie rootfs before we launch to crowd funding sites.
- TODOs
  Test flight with APM3.3 + Kernel 4.1.9 rt
- Outputs
  Test flight logs.(pic/movies)

**Comment by onceme** [comment]
How is this going? I have updated Copter-3.3-BH-develop, please update your local copy

**Comment by onceme** [comment]
The crash has been fixed, commit is here: https://github.com/bithollow/ardupilot/commit/86f97f31ab8c91f089664bf1b2ce36a0af2138b1

Please continue to check other parts. I don't have the board in handle, from GCS, the MPU6050 data looks strange.

**Comment by onceme** [comment]
The crash was caused by other's change, not ours. It is in Compass.cpp

**Comment by droneboost** [comment]
I've tested the latest Copter-3.3-BH-develop code without ESC mounted, it seems work well,GCS status tracing is very stable, but we still need to test it with ESC and motor before switch this branch to main dev branch.

**Comment by onceme** [comment]
Please test this based on kernel 4.1.5/APM Copter-3.3 rc12, don't wait for me, I don't know when they would update kernel/APM again, so till the due date of M1, 4.1.5/rc12 might be the final software version.

tick tock, tick tock...

**Comment by droneboost** [comment]
BH3.3 Sensor data is not stable on kernel 4.1.5(rt) + latest Debian jessie rootfs.

**Comment by droneboost** [comment]
estimate 4 days to finish the test flight with Muzu-15.

**Comment by droneboost** [comment]
Copter-3.3-BH-Develop:
D.B.'s 0.2 board: restart ardupilot.service several times before ardupilot work normally.
Muzu-15's 0.2 board: ardupilot.service keeps restarting, never work normally.

Master:
D.B. and Muzu-15's 0.2 board both work normally.

RC controller will disturb wifi hostap. Will try to change wifi hostap channel. Current setting 2437mhz, channel 6.  (12/9)
Channel  Frequency(MHz)  North America  Japan  Most of world 
1             2412                       Yes                  Yes       Yes
2             2417                      Yes                   Yes       Yes
3             2422                      Yes                   Yes       Yes
4             2427                      Yes                   Yes       Yes
5             2432                      Yes                   Yes       Yes
6             2437                      Yes                   Yes       Yes
7             2442                      Yes                   Yes       Yes
8             2447                      Yes                   Yes       Yes
9             2452                      Yes                   Yes       Yes
10           2457                      Yes                   Yes       Yes
11           2462                      Yes                   Yes       Yes

**Comment by droneboost** [comment]
Test flight has been done and movie has been recored.
APM seems very stable in spite of operator's suck skill.
I close this issue.

**Comment by onceme** [comment]
Your first flight looks better than mine:)
