### ISSUE TITLE
[M3][SW][Low] Improve debian bootup time

### ISSUE THREAD

**Issue by droneboost** [bithollow/bitforge#26]
- Background
  Currently, it takes more than 10s to boot up our flight control board, our target bootup time are 8s(kernel boot/services startup) + 3s(APM startup).
- TODOs
  Reduce Linux kernel boot up time to 8s.
- Outputs
  Latest kernel and rootfs image

**Comment by droneboost** [comment]
Deadline is 10/30

**Comment by droneboost** [comment]
Estimate 2 days to finish this issue.

**Comment by droneboost** [comment]
Just memo, will make a reference to the following page later:
https://wiki.archlinux.org/index.php/Improve_boot_performance

**Comment by droneboost** [comment]
Since this is a trivial task in M2 and M2 is delayed for a long time, I suggest to defer this issue to next Milestone, how do you think, BH guys?

**Comment by onceme** [comment]
I suggest remove this issue from Milestone for now. Once we have time to fine tune BH sw, then pull it back.

**Comment by muzi-15** [comment]
OK， got it. defer to next Mil..

**Comment by muzi-15** [comment]
need about 10 days.

**Comment by muzi-15** [comment]
ETA:4/15

**Comment by muzi-15** [comment]
eth0: dhcp 
boot time:
Startup finished in 3.648s (kernel) + 1min 32.665s (userspace) = 1min 36.313s

detailed time:
        1min 6.893s networking.service
         10.117s rsyslog.service
          1.467s dnsmasq.service
          1.131s systemd-logind.service
           723ms lighttpd.service
           706ms resolvconf.service
           703ms systemd-udev-trigger.service
           630ms hostapd.service
           513ms rc-local.service
           507ms systemd-setup-dgram-qlen.service
           468ms dhcpcd.service
           434ms systemd-modules-load.service
           324ms kmod-static-nodes.service
           314ms systemd-journal-flush.service
           313ms systemd-random-seed.service
           298ms systemd-tmpfiles-setup-dev.service
           287ms systemd-remount-fs.service
           248ms systemd-sysctl.service
           241ms dev-mqueue.mount
           193ms sys-kernel-config.mount
           176ms systemd-user-sessions.service
           168ms sys-kernel-debug.mount
           168ms hciuart.service
           142ms systemd-tmpfiles-setup.service
           102ms bluetooth.service
            95ms hwclockfirst.service
            70ms systemd-update-utmp.service
            67ms udev-finish.service
            63ms systemd-update-utmp-runlevel.service
            47ms boot-firmware.mount
            41ms systemd-rfkill@rfkill0.service
            37ms systemd-udevd.service
            23ms systemd-rfkill@rfkill1.service

**Comment by muzi-15** [comment]
eth0: manual
 boot time:
Startup finished in 3.427s (kernel) + 16.768s (userspace) = 20.196s
detailed time:
          1.684s dnsmasq.service
           961ms lighttpd.service
           950ms systemd-logind.service
           847ms dhcpcd.service
           847ms networking.service
           787ms resolvconf.service
           785ms systemd-udev-trigger.service
           667ms hostapd.service
           577ms systemd-setup-dgram-qlen.service
           528ms rc-local.service
           496ms systemd-modules-load.service
           458ms hwclockfirst.service
           330ms kmod-static-nodes.service
           313ms systemd-random-seed.service
           300ms dev-mqueue.mount
           298ms systemd-tmpfiles-setup-dev.service
           297ms systemd-remount-fs.service
           228ms sys-kernel-debug.mount
           213ms systemd-sysctl.service
           194ms sys-kernel-config.mount
           176ms hciuart.service
           172ms rsyslog.service
           151ms boot-firmware.mount
           124ms systemd-journal-flush.service
           102ms bluetooth.service
            70ms systemd-user-sessions.service
            53ms systemd-update-utmp-runlevel.service
            52ms systemd-update-utmp.service
            49ms systemd-tmpfiles-setup.service
            47ms udev-finish.service
            37ms systemd-udevd.service
            33ms systemd-rfkill@rfkill0.service
            21ms systemd-rfkill@rfkill1.service

**Comment by muzi-15** [comment]
most of the start time has spent on networking.service starting. about 1minute.
if disable network service, the start time is about 20s.
Kernel starting spent about 3.5s.
userspace starting spent about 15s

**Comment by muzi-15** [comment]
current bootup time was acceptable, so there is no need keep on improve it.
