### ISSUE TITLE
[M3][High][Mechanical] Design BH protect case

### ISSUE THREAD

**Issue by droneboost** [bithollow/bitforge#27]
- Background
  We need a plastic case to protect RPI+BH, especially to protect the SD card.
- TODOs
  Find a free and easy using 3D modeling tool.
  Create 3D model of BH and export 3D print files.
  Find a 3D printing service provider on TaoBao or Tmall to print the case.
- Outputs
  BH protect case

**Comment by onceme** [comment]
Please add Background/TODOs/Outputs

**Comment by droneboost** [comment]
New finding!

Autodesk released a free and easy using 3D modeling tools - Autodesk 123D. 
Benefited with the free policy, people are forging a 3D design community, where people can offering free or no-free 3D modeling designs, for raspberrypi, I found a free 3D modeling design at http://www.123dapp.com/123D_Design/Pi-case/3218365, seems we can re-use this model to customize BH protect case.

**Comment by droneboost** [comment]
googled 3D printing service price, priced in per gram unit.

![image](https://cloud.githubusercontent.com/assets/10015032/10926839/c2ca43cc-82d5-11e5-937a-ef0cb6941238.png)

more prices,
http://www.3dreamwell.com/index.php?option=com_content&view=article&id=36&Itemid=158
http://www.3d-print.cn/materials-comparison

**Comment by onceme** [comment]
There are a lot of 3d printers on hobbyking with good price

**Comment by onceme** [comment]
Your googled price is for the material, not the printer itself.

**Comment by droneboost** [comment]
``` shell
3. Find a 3D printing service provider on TaoBao or Tmall to print the case.
```

**Comment by muzi-15** [comment]
it is hard to evaluate details workdays, generally 20 days

**Comment by muzi-15** [comment]
The Price was bellow:

huangzetao888 (13:20:07):
这个大量加工的话一个大概是40元左右
单独做几个的话出样费大概400元左右
yongxinwu_2008 (13:23:54):
了解，多谢

yangniu1986 (13:08:58):
要不要喷漆，还是本色就行？
yongxinwu_2008 (13:09:06):
本色就行
yangniu1986 (13:09:32):
预估会在300-500，
yongxinwu_2008 (13:09:35):
样品的，最简单就行，量产的话有颜色

**Comment by muzi-15** [comment]
ETA: 4/15

**Comment by muzi-15** [comment]
the box design has finished, there are total 4 pieces.

**Comment by droneboost** [comment]
Good!

**Comment by droneboost** [comment]
Show us the picture

**Comment by muzi-15** [comment]
it seems can not upload pictures. please see it by  wechat.

**Comment by muzi-15** [comment]
![Uploading BH box.png…]()

**Comment by droneboost** [comment]
check comments in your input textbox

 "Attach files by dragging & dropping,  选择文件 selecting them, or pasting from the clipboard."

**Comment by droneboost** [comment]
![pic_upload](https://cloud.githubusercontent.com/assets/10015032/26349067/4a8c6550-3fe1-11e7-91a3-344a23afae05.png)

**Comment by muzi-15** [comment]
![bh box](https://cloud.githubusercontent.com/assets/11763815/26388331/45d8182e-4086-11e7-91df-5e4731e2b220.png)

**Comment by droneboost** [comment]
Good!

**Comment by droneboost** [comment]
Have you upload the design file to bitbucket?
