### ISSUE TITLE
[M2][High][HW] BH board (0.2) delivery

### ISSUE THREAD

**Issue by muzi-15** [bithollow/bitforge#28]
Requirements:
1.  2 boards: A for RPI2 and B for MCU(like stm32).
2.  6050 or 9250
3.  drivers packages and demos for BH board

Output：
1. model A and model B which can sell on the market.
2. some useful demos

**Comment by onceme** [comment]
> 1. drivers packages and demos for BH board
>    I think this could be put in another issue, and more details are required. Such as driver packages list, demo list etc.

**Comment by muzi-15** [comment]
OK, it is good, it should be split into some features and more issues

**Comment by onceme** [comment]
2 boards: A for RPI2 and B for MCU(like stm32).

model A:
definition: it is the updated and fine tuned version of current BH, could be delivered to people other than the three of us
- a decent board name (I think "BH" is just temporary)
- use MPU9250 SPI
- put single color leds closer to each other
- black or blue PCB
- 40 long pins male connector to 2 of 40 pins female connectors (on the top and bottom separately)
- remove jump wires
- change D4 to red, D5 to yellow, D6 to blue, D1 to white
- connect D2 to GPS directly 
- change crystal oscillator to SMT (Surface Mount Technology) version, support devices which can use external crystal oscillator
- add I2C EEPROM for HAT standand

model B:
definition: it is the MCU equipped version of model A, the MCU can be used as standalone pilot software processor
- add MCU (stm32?)

**Comment by onceme** [comment]
Three owners all agree to close, because module B canceled
