### ISSUE TITLE
[M1][High] Update to Linux RT 4.1.x

### ISSUE THREAD

**Issue by onceme** [bithollow/bitforge#32]
- Background
  Support Raspberry PI  Linux kernel upstream
- TODOs
  Keep updating Linux kernel to the latest for RPI2 in M1
- Output
  Source code push into bithollow/linux

**Comment by onceme** [comment]
preempt_rt 4.1.5-rt5 could be patched to RPI 4.1.5 kernel

**Comment by droneboost** [comment]
preempt_rt 4.1.5-rt5 will be included in M1. Update the kernel in M2 again.
Close this issue.

**Comment by onceme** [comment]
update new branch remotes/origin/rpi-4.1.y-preempt-rt-4.1.7. This is the final for M1
