### ISSUE TITLE
[M1][High] prepare BH0.2A layout

### ISSUE THREAD

**Issue by muzi-15** [bithollow/bitforge#35]
output: layout documents

**Comment by onceme** [comment]
When can we start reviewing?
Could you maintain this layout file somewhere in the repo? So everyone can easily have a copy

**Comment by onceme** [comment]
My review comments to Layout so far:
- Where is "BH" logo on the board?
- P5 "PWMX" label looks wrong for the new added three, so as to label of its pin heads
- P5 needs "+","-","Sig" label
- Connect all the middle of the pins in P5 to 5V
- Single color leds could be more closer if moving label R7~R9, D4~D6 aside
- P6 instruction label is missing
- I think P6 pin matrix should be the following, why seems different now?

| left | middle | right |
| --- | --- | --- |
| GND | GND | VCC |
| GPIO26 | GPIO21 | GPIO20 |
| GPIO13 | GPIO16 | GPIO19 |
| GPIO12 | GPIO06 | GPIO05 |
- Single colors please refer here: [APM 2.5 leds](http://copter.ardupilot.com/wiki/common-apm-board-leds/)
  - A (GPIO-17, D4): red
  - B (GPIO-18, D5): yellow
  - C (GPIO-22, D6): blue
  - GPS (D2): blue
- Introduce PWM 12?
- Replace AT24C02 to AT24C16?
- The 2*20 pin connector, we can cut the pins to suit the size, so the board size remains HAT size. Best fit refer [here](http://www.toby.co.uk/datasheets/section4/REF-1826xx-0x.pdf?revDate=11032015125910)

**Comment by droneboost** [comment]
Close 9/29 PM10:12
