### ISSUE TITLE
[M1][High] prepare BOM and parts (9/28 => 10/8)

### ISSUE THREAD

**Issue by muzi-15** [bithollow/bitforge#36]
output: 
           BOM list file, full parts

**Comment by droneboost** [comment]
In processing(9/30),  Create BOM table on wiki <= Muzu-15

ETA: 10/8 to get all e-parts

**Comment by muzi-15** [comment]
![image](https://cloud.githubusercontent.com/assets/11763815/10408422/a0c1d10a-6f2f-11e5-88c3-26a4a7b19939.png)

**Comment by muzi-15** [comment]
![image](https://cloud.githubusercontent.com/assets/11763815/10408437/1635ecc8-6f30-11e5-8ba0-ca42d25a7094.png)

**Comment by muzi-15** [comment]
Done

**Comment by muzi-15** [comment]
Done. Close

**Comment by onceme** [comment]
Upload BOM and layout to bitbucket

**Comment by muzi-15** [comment]
please refer to: :git clone https:bitbucket.org/bithollow/bh-hardware-infos.git

**Comment by onceme** [comment]
@muzi-15 please add actual BOM list and layout to the repo

**Comment by muzi-15** [comment]
has uploaded .
