### ISSUE TITLE
[M2][Low] Create BH2.0 pin layout graph

### ISSUE THREAD

**Issue by droneboost** [bithollow/bitforge#39]
- Background:
  - This graph will explain all the BH pins.
- TODOs:
  - 1. PWM output
  - 2. ADC input
  - 3.  I2C/SPI/UART
  - 4.  RCInput
- Outputs：
  - Document that include detailed BH pins explanation which will help the developer to use to BH board easily.
- 2 days

**Comment by onceme** [comment]
Please add Background/TODOs/Outputs

**Comment by muzi-15** [comment]
- Background:
  - This graph will explain all the BH pins.
- TODOs:
  - 1. PWM output
  - 2. ADC input
  - 3.  I2C/SPI/UART
  - 4.  RCInput
- Outputs：
  - Document that include detailed BH pins explanation which will help the developer to use to BH board easily.
- 2 days
