### ISSUE TITLE
Collect chip informations

### ISSUE THREAD

**Issue by droneboost** [bithollow/bitforge#4]
1 PCA9685
   PCA9685.pdf
   UM10204_I2C_Specification_UM.pdf

**Comment by onceme** [comment]
I think we still need them:
- MPU6000/6050
- MPU9250
- MS5611
- HMC5883L/5843
- U-Blox M8N

**Comment by onceme** [comment]
@droneboost consider to close this issue

**Comment by droneboost** [comment]
Since BH first edition has come out, I close this issue.
