### ISSUE TITLE
[M2][Medium] Merge our changes to ardupilot.git upstream

### ISSUE THREAD

**Issue by droneboost** [bithollow/bitforge#40]
- Background
  Merge BH related changes to upstream
- TODOs
  - discuss with APM chargers
  - prepare latest master branch of upstream
  - divide changes and commit
  - launch pull request to upstream
  - acceptance by APM chargers
- Outputs
  Source code into upstream

**Comment by onceme** [comment]
I need at least 20 days to finish this if APM maintainer agreed.

**Comment by onceme** [comment]
APM upstream developers agreed to accept our pull request.

https://groups.google.com/forum/#!topic/drones-discuss/oE1alXaXNzM

**Comment by onceme** [comment]
latest master branch is prepared

**Comment by onceme** [comment]
pull request launched here: https://github.com/diydrones/ardupilot/pull/3138

**Comment by onceme** [comment]
http://elinux.org/RPi_BCM2835_GPIOs

**Comment by droneboost** [comment]
Good page!

**Comment by onceme** [comment]
pull request launched again: https://github.com/diydrones/ardupilot/pull/3244

**Comment by onceme** [comment]
https://github.com/diydrones/ardupilot/pull/3282

**Comment by onceme** [comment]
Finally, we have our first time to merge BH support code to upstream. Check comment in https://github.com/diydrones/ardupilot/pull/3282. This issue could be closed.

**Comment by droneboost** [comment]
A big leap forward, Great job!

**Comment by onceme** [comment]
check [this](https://www.scribd.com/doc/127599939/BCM2835-Audio-clocks) for bcm 2835 pcm div/ctrl registers
