### ISSUE TITLE
[M2][High] Create website BH specification page

### ISSUE THREAD

**Issue by droneboost** [bithollow/bitforge#41]
- Background:
  - this document will detailed explain the BH 0.2 hardware and software features 
- TODOs:
  -  Hardware:
    - 1. All sensors explanation
    -  2. All the IN/OUT pins explanation 
    - 3. May be include the board performance.
  -  Software
    - 1. software features(APM support) and performance
- Outputs
  - updated the BH web sites with above contents
- 5 days

**Comment by onceme** [comment]
Please add Background/TODOs/Outputs

**Comment by muzi-15** [comment]
- Background:
  - this document will detailed explain the BH 0.2 hardware and software features 
- TODOs:
  -  Hardware:
    - 1. All sensors explanation
    -  2. All the IN/OUT pins explanation 
    - 3. May be include the board performance.
  -  Software
    - 1. software features and performance
- Outputs
  - updated the BH web sites with above contents
- Precondition:
     -ISSUE #45 has been finished.
- 5 days

**Comment by muzi-15** [comment]
the initial version has finished。 so close it，

**Comment by onceme** [comment]
I think you should re-size the photos

**Comment by onceme** [comment]
created bithollow/manifests#52 to re-size photos, close this one
