### ISSUE TITLE
[M2][High] Crowd funding plan

### ISSUE THREAD

**Issue by droneboost** [bithollow/bitforge#42]
- Background
  A plan about how to do crowd funding, include using which crowd funding platform, the detailed steps, how much fund we expect in the first phase, what we can provide if succeeded etc.
- TODOs
  - decide which crowd funding platform
  - investigate detailed steps, what we need to put on the platform
  - how much fund we expect in the first phase, what we will do with these fund
  - what we can provide if the funding quantity is reached
- Outputs
  The actual plan

**Comment by onceme** [comment]
Please add Background/TODOs/Outputs

**Comment by onceme** [comment]
ETA 7 days

**Comment by onceme** [comment]
[wyzowl](https://www.wyzowl.com/) a great video maker that could benefit our crowding video. There are suggestions, examples, skills teaching

**Comment by onceme** [comment]
![directions](http://www.inc.com/uploaded_files/image/inc-magazine-crowdfunding-infographic-june-2013_26652.jpg)

**Comment by onceme** [comment]
[Crowding basics](https://en.wikipedia.org/wiki/Comparison_of_crowdfunding_services) that we must know.

**Comment by onceme** [comment]
[国内的众筹平台](https://www.zhihu.com/question/21022884)

**Comment by onceme** [comment]
一堆国内平台里面选出两个：
- [点名时间](http://www.demohour.com/guidelines/project)项目规范
- [创客星球](http://hello.themakers.cn/?page_id=991)服务协议

个人更倾向于[创客星球]，不过不清楚其背后的投资团队规模，而且其限制不能同时在国内外众筹平台同时发起。相比之下[点名时间]的投资团队透明度更高，只限制不能同时在国内众筹平台同时发起。两者都是AoN(All or Nothing)类的，筹资时间最长60天，筹资成功以后3个月内提供承诺的投资人回报。

**Comment by onceme** [comment]
Because the crowd funding usually has a time limit, for the type of AoN, if we can't reach our funds quantity in time, they will be returned to investors. So one important thing is that we should let people as many as possible know we are going to launch a crowd funding. Thus, the idea and our plan should go public into the social network before launching funding.

**Comment by onceme** [comment]
# Plan

### Crowd funding model
- [Funding model: money for goods](https://en.wikipedia.org/wiki/Comparison_of_crowdfunding_services#Money_for_goods)
- [non-equity](https://en.wikipedia.org/wiki/Equity_crowdfunding)

### Crowd funding platform
- [Indeigogo](https://www.indiegogo.com/learn-how-to-raise-money-for-a-campaign)
  - [Keep it All (KiA)](https://en.wikipedia.org/wiki/Comparison_of_crowdfunding_services#Money_for_goods)
  - Register a company bank account
  - Register a company credit card
  - Register a company paypal account [(1.2% withdraw to Chinese bank account)](https://www.paypal.com/c2/cgi-bin/webscr?cmd=_display-withdrawal-fees-outside)
  - [Fee & Pricing](https://support.indiegogo.com/hc/en-us/articles/204456408)
    - 5% platform fee
    - 3% + 0.3USD third-party credit card fees
  - Account: login with bithollow.feedback facebook account
  - Goal: 5000USD (57 pcs, cost 3563USD, surplus 1437USD) 
- [Demohour](http://www.demohour.com/guidelines/project)
  - [All or Nothing (AoN)](https://en.wikipedia.org/wiki/Comparison_of_crowdfunding_services#Money_for_goods)
  - Register a company alipay account
  - [Fee & Pricing](http://www.demohour.com/faq?chapter=section_3#a40)
    - 3% platform fee
    - Account: login with bithollow.feedback weibo account
  - Goal: 28450CNY (50 pcs, cost 20000CNY, surplus 8450CNY)

### Contents on platform
- Story about why we are doing this
- Introduction video and photos prepared in https://github.com/bithollow/manifests/issues/50
- BH HAT
  - Specification
  - Target users
- Two sets of funding
  - Set1. 3USD on Indeigogo, 10RMB on Demohour
    - Just because one like the idea
    - Reward
      - Put their names on bithollow website as donator
  - Set2. 89USD on Indeigogo, 569RMB on Demohour
    - They want to fly BH with RPI or create BH + RPI projects
    - Reward
      - Bare bone BH board without connecting wires
      - Put their names on bithollow website as donator
- Funds will be used to
  - Produce BH for the board in Set2
  - Sustain website cost
  - Pay funding platform
  - Pay bank and tax
  - Support Bithollow expansion
    - Build distribution channel
    - Cooperate with sales agency in HongKong
- Next funding plan
  - What we do next if BH HAT kickoff

### References
- [How to choose a crowdfunder](http://www.inc.com/magazine/201306/eric-markowitz/how-to-choose-a-crowdfunder.html)
- [Crowding basics](https://en.wikipedia.org/wiki/Comparison_of_crowdfunding_services)
- [Generosity](https://generosity.com), for nonprofits and social causes, check out our new site, Generosity by Indiegogo

**Comment by droneboost** [comment]
If we raised money, should we donate a very tiny portion of the money to APM or APM planner project?

**Comment by onceme** [comment]
@droneboost no, we contribute source code to APM projects only. of course you can do that personally

**Comment by onceme** [comment]
We have discussed this plan, close.
