### ISSUE TITLE
[M2][Medium] Establish product feedback channels

### ISSUE THREAD

**Issue by droneboost** [bithollow/bitforge#44]
- Background
  After we launch our flight control board to the market, we need to establish communication channels to get feedback from our customers.
- TODOs
  Forum:  51mx, amobbs, playuav
  SNS: Twiter, Wechat, Weibo
  Email address 
- Outputs
  Forum/SNS/Email accounts associate with notify email.
  Feedback channel test passed

**Comment by onceme** [comment]
Please add Background/TODOs/Outputs

**Comment by droneboost** [comment]
Estimate 1 day to handle this issue.

**Comment by droneboost** [comment]
I'll try to apply a gmail address "bithollow@gmail.com", then associate this gmail with all kinds of Feedback channels and set email forward to your personal email address from this gmail.

@onceme 
@muzi-15 

Please give me your personal email addresses.

**Comment by onceme** [comment]
aarons.wang@gmail.com

**Comment by droneboost** [comment]
bithollow.feedback@gmail.com has been created.

**Comment by onceme** [comment]
I received emails in my mail box, good!

**Comment by droneboost** [comment]
Would you please forward the email to me, I need the verification code to finish email forwarding setting.

**Comment by onceme** [comment]
![image](https://cloud.githubusercontent.com/assets/5754278/11244778/59a2e66c-8e4a-11e5-9cff-7ffceb462651.png)

**Comment by droneboost** [comment]
You have to click the confirm link address at the bottom of your email.

Gmail: bithollow.feedback@gmail.com
PlayUav username: bithollow
51MX username: bithollow
Twitter username: bithollow
facebook username: bithollow
Weibo username: bithollow.feedback@gmail.com

**Comment by droneboost** [comment]
Issues:
1. Twitter account is frozen, need to re-active
2. Gmail only has one effective email forwarding setting.

**Comment by onceme** [comment]
solution for your issue 2., please try http://gappstips.com/gmail/automatically-forward-emails-to-multiple-recipients-in-gmail/

**Comment by onceme** [comment]
probable solution for your issue 1., a virtual phone number, check here https://www.youtube.com/watch?v=lzmrQbV9AEM&noredirect=1

**Comment by droneboost** [comment]
Thanks to Aaron's suggestion, Gmail foward problem has been fixed.
Every email received by bithollow.feedback@gmail.com will be forwarded to aarons.wang@gmail.com, wxyongxinwu@gmail.com, fcao2008@gmail.com.

**Comment by onceme** [comment]
@droneboost I just received "forward test" in my gmail

**Comment by droneboost** [comment]
Twitter has fixed the access problem for us, so close this issue.

**Comment by droneboost** [comment]
http://www.comm100.com/

Hobbyking use it to handle online customer service.
