### ISSUE TITLE
[M2][High] Create website documentation

### ISSUE THREAD

**Issue by onceme** [bithollow/bitforge#46]
- Background
-  Prepare document pages for users and developers.
  -  Usually will be done by @muzi-15 and @droneboost, first is @muzi-15, please assign to   @droneboost after 'basic pages' finished. Could be assign to @onceme if necessary.
- TODOs
  - basic pages, Hardware Setup(RPI+BH+ESC+RC receiver+etc.) 
  - github exist wiki pages
  - introduce driver pages
  - introduce app pages
- Outputs
  - Makedown pages
- 6 days

**Comment by muzi-15** [comment]
please droneboost update the related contents.

**Comment by onceme** [comment]
@muzi-15 you can assign this to @droneboost if necessary

**Comment by droneboost** [comment]
muzi-15, I've commit my part, so I assign back this issue to you.

**Comment by muzi-15** [comment]
the initial version has committed， if any problem please comment at  [M2] optimize web page, #56
