### ISSUE TITLE
[M2][High] Design/implement driver interfaces demonstration

### ISSUE THREAD

**Issue by onceme** [bithollow/bitforge#48]
- Background
  Prepare driver interfaces demonstration by @bithollow/owners.
- TODOs
  - MPU9250
  - MS5611
  - PCA9685
  - Ublox NEO M8N
  - DS1339
  - ADS1115
  - EEPROM(optional)
- Outputs
  - source code into repo
- Firstly will prepare the IMU modules
  - 7 days

**Comment by muzi-15** [comment]
has committed.
