### ISSUE TITLE
[M2][High] Design/implement application demonstration

### ISSUE THREAD

**Issue by onceme** [bithollow/bitforge#49]
- Background
  - Prepare application demonstration by @bithollow/owners.
- TODOs
  - IMU
  - LED
  - GPS
  - BARO
  - Brushless motor
- Outputs
  - source code into repo
- Firstly will prepare the IMU module 
  - 7 days

**Comment by muzi-15** [comment]
code has committed， then close it

**Comment by muzi-15** [comment]
add servo demo to drive the motor.

**Comment by muzi-15** [comment]
update IMU app.

**Comment by muzi-15** [comment]
the demo app has been uploaded,

**Comment by muzi-15** [comment]
has commit ahrs app, the usage will explain in Web site.
