### ISSUE TITLE
[M?] enable I2C-0

### ISSUE THREAD

**Issue by muzi-15** [bithollow/bitforge#53]
Output:
          1.  enable the I2C-0 bus。
          2. can read/write EEPROM

**Comment by droneboost** [comment]
1 is Done.

Current BH kernel config - bcm2709_preempt_rt_defconfig - already enabled device tree support.
CONFIG_BCM2709_DT=y

So the only thing we need to do is making a DT sensible kernel image with mkknlimg and copy dtb to the target directory, please check following commands in mksd6.sh

``` shell
sudo ../tools/mkimage/mkknlimg --dtok ../linux/build/arch/arm/boot/zImage mnt/firmware/kernel.img
sudo cp ../linux/build/arch/arm/boot/dts/bcm2709-rpi-2-b.dtb  mnt/firmware/bcm2709-rpi-2-b.dtb
sudo cp -a ../linux/build/arch/arm/boot/dts/overlays mnt/firmware/
```

To enable i2c and spi, just add following lines to /boot/firmware/config.txt

``` shell
dtparam=i2c_arm=on     #i2c-0
dtparam=i2c_vc=on        #i2c-1
dtparam=spi=on
```

For i2c device layer driver, we still need to append them in to /etc/modules, for instance, at24, rtc-1307

**Comment by onceme** [comment]
@droneboost, great job!

**Comment by droneboost** [comment]
Hi Aaron, I have a question,. where did you get the bcm2709_preempt_rt_defconfig from?

**Comment by onceme** [comment]
It is derived from bcm2709_defconfig, this one is in RPI kernel tree.
What I did to it is enabling several preempt rt configs in menuconfig after patching, then save it as the current name you see.

**Comment by droneboost** [comment]
@muzi-15 , please update the method of lower i2c-0 bus speed.

**Comment by droneboost** [comment]
Closed by add device tree!
