### ISSUE TITLE
[M3][High] Visioning navigation feasibility study

### ISSUE THREAD

**Issue by onceme** [bithollow/bitforge#59]
- Background
  In order to implement visioning navigation, a feasibility is necessary
- TODO
  - [x] Collect related documents
  - [x] Overall of Pushbroom software ARCH.
  - [x] Pushbroom data process path
  - [x] Reusable software components
  - [x] Idea of implementing on BH
- Output
  - feasibility report on issue
  - hardware model/usage/how-to connect to BH+RPI
  - software blocks/how-to connect to ArduPilot

**Comment by droneboost** [comment]
E.T.A 2017/2/28

**Comment by droneboost** [comment]
E.T.A Mid of March 2017

**Comment by droneboost** [comment]
1. need to build & install [lcm](https://lcm-proj.github.io/index.html)
2. need to build & install [libbot2](https://github.com/RobotLocomotion/libbot2)
3. need to build & install [Pronto state estimator](https://github.com/robotperception/pronto-distro)
    => before build Pronto, run "sudo apt-get install git build-essential libglib2.0-dev openjdk-6-jdk python-dev cmake gtk-doc-tools libgtkmm-2.4-dev  freeglut3-dev libjpeg-dev libtinyxml-dev libboost-thread-dev libgtk2.0-dev python-gtk2 mesa-common-dev libgl1-mesa-dev libglu1-mesa-dev libqwt-dev"
4. need to build & install [mavlink](https://github.com/mavlink/mavlink)
5. need to build & install [mavconn](https://github.com/pixhawk/mavconn)
6. need to build & install [libdc1394](https://github.com/pixhawk/libdc1394)
    => Also depends on libv4l1

**Comment by droneboost** [comment]
Here is the full build steps written by Flight's Author - Andy Barry 
[View build steps](https://github.com/andybarry/flight/wiki)

**Comment by droneboost** [comment]
Progress update in 2/7th:
After installing prerequisite packages and libraries according to Andy Barry and do some modifications, was able to build the "flight" project, next step is to dig into the software ARCH.

Picture was captured by run command "bot-procman-sheriff -l $HOME/realtime/config/bot-procman-desktop.cfg"
![screenshot from 2017-02-07 09 00 14](https://cloud.githubusercontent.com/assets/10015032/22673360/a7f34da0-ed14-11e6-8093-c41a04e11358.png)

**Comment by droneboost** [comment]
In order to run the flight project on board, the current 6GB rootfs space is no enough. 
Andy use 64GB Flash.

**Comment by onceme** [comment]
> After installing prerequisite packages and libraries according to Andy Barry and do some modifications, was able to build the "flight" project, next step is to dig into the software ARCH.

It is good to hear:)

> In order to run the flight project on board, the current 6GB rootfs space is no enough.
Andy use 64GB Flash.

You'd to create a new mksd script for this.

**Comment by droneboost** [comment]
[Basic principle](http://wenku.baidu.com/link?url=EHrnviXw9Iwz3MYJno_xZySpR3EMPZIKXuizZuxc9PEH-mXWhnMGqvMCUEeG9_hv1RBESSDI_EU6ERZnhValUFygrroQQmb2e60CDSIYhh7) of stereo image process

**Comment by droneboost** [comment]
ProcessImage
    =>Remap (8 threads)
    =>Interest_OP (8 threads)
    =>Stereo (8 threads)

**Comment by droneboost** [comment]
单目相机标定：http://sourishghosh.com/2016/camera-calibration-cpp-opencv/
双目相机标定：http://sourishghosh.com/2016/stereo-calibration-cpp-opencv/

其他参考：
http://www.cnblogs.com/daihengchen/p/5492729.html

DUAL_CAM_GLOBAL_V2 stereo camera calibration files:
Left Camera:
[cam_left_calibration.xml.txt](https://github.com/bithollow/bitforge/files/779197/cam_left_calibration.xml.txt)

Right Camera:
[cam_right_calibration.xml.txt](https://github.com/bithollow/bitforge/files/779198/cam_right_calibration.xml.txt)

Stereo Calibration:
[cam_stereo.xml.txt](https://github.com/bithollow/bitforge/files/779248/cam_stereo.xml.txt)

DUAL_CAM_GLOBAL_V2 stereo camera calibration files generated by Flight builtin calibration program:
[calib-raspberry-dual_global_cam.zip](https://github.com/bithollow/bitforge/files/788914/calib-raspberry-dual_global_cam.zip)

Flight calibration program: $flight_dir/sensors/stereo/stereo_camera_calibrate/stereo_calibrate

Camera calibration chessboard:
![pattern](https://cloud.githubusercontent.com/assets/10015032/24937961/dcc97a84-1f66-11e7-8ccb-420ecc22bacc.png)

**Comment by droneboost** [comment]
E.T.A 2017/4/21

**Comment by droneboost** [comment]
Mavlink packet anatomy:
![image](https://cloud.githubusercontent.com/assets/10015032/24533709/01084250-15fc-11e7-8cb7-be20b461050c.png)

**Comment by droneboost** [comment]
Use message REQUEST_DATA_STREAM (#66) to request data from mavlink device.

P.S. THIS INTERFACE IS DEPRECATED. USE SET_MESSAGE_INTERVAL INSTEAD.

**Comment by droneboost** [comment]
Finally able to get mavlinkbrige and the whole system work now.
Next step is to tune the system.
![screenshot from 2017-04-01 13 50 00](https://cloud.githubusercontent.com/assets/10015032/24575816/74a4d35e-16e2-11e7-97e9-b9119254990e.png)

**Comment by onceme** [comment]
It looks nice, great job!

**Comment by droneboost** [comment]
Modified repos:
flight: https://github.com/droneboost/flight.git                           branch: master
mavconn: https://github.com/droneboost/mavconn.git             branch: bithollow
mavlink: https://github.com/droneboost/mavlink.git                  branch: bithollow
proton: https://github.com/droneboost/pronto.git                      branch: bithollow
proton-distro: https://github.com/droneboost/pronto-distro.git  branch: bithollow

No-modified repos:
libbot2: https://github.com/droneboost/libbot2.git                     branch: master

**Comment by droneboost** [comment]
build dependencies:
sudo apt-get install subversion autopoint gtk-doc-tools \
git build-essential cmake libglib2.0-dev libgtop2-dev \
gpsd libgps-dev libboost-all-dev libgsl0-dev \
libusb-1.0-0-dev libv4l-dev libv4l-0 \
libgtop2-dev libaio-dev libgtk2.0-dev pkg-config \
libglibmm-2.4-dev openjdk-6-jdk python-dev cmake \
libgtkmm-2.4-dev  freeglut3-dev libjpeg-dev \
libtinyxml-dev libboost-thread-dev python-gtk2 \
mesa-common-dev libgl1-mesa-dev libglu1-mesa-dev libqwt-dev \
libpcl1.7 autotools-dev libasound2-dev openjdk-7-jre libopencv-dev libdc1394-22-dev

sudo pip install future

**Comment by droneboost** [comment]
[BH_RobotVision_VisionNavigation_Ver1.pptx](https://github.com/bithollow/bitforge/files/1040468/BH_RobotVision_VisionNavigation_Ver1.pptx)

Upload analyze document and close the issue.

**Comment by droneboost** [comment]
[bot-procman-rpi3 .txt](https://github.com/bithollow/bitforge/files/1046716/bot-procman-rpi3.txt)

Upload libbot config file example.  (change postfix from .txt to .cfg)

Run command "bot-procman-deputy -u udpm://239.255.76.67:7667?ttl=1" on flight control board and monitor PC, then run command “bot-procman-sheriff /home/lute/realtime/config/bot-procman-rpi3.cfg” on monitor PC.
