### ISSUE TITLE
[M3][High] SD card image release version

### ISSUE THREAD

**Issue by onceme** [bithollow/bitforge#60]
- Background
  milestone will release full-blown products, including but not limited to BH HAT, RPI sd image, documents, this issue is for RPI sd image preparation.
- TODO
  - [x] upgrade rootfs to Debian jessie the latest
  - [x] upgrade kernel
  - [x] support bt
- Output
  - [x] sd card image host on bitburge

**Comment by onceme** [comment]
E.T.A 2016/12/31

**Comment by onceme** [comment]
This project looks good to make web-gui wifi ap: https://github.com/billz/raspap-webgui

**Comment by droneboost** [comment]
I'll check it.

**Comment by onceme** [comment]
enable bt on Raspberry Pi 3: https://gist.github.com/onceme/8131435e478d7691a05b1cec0ee080a0

**Comment by onceme** [comment]
good experience about how to deny starting daemon process while doing 'apt-get install' in chroot: https://wiki.debian.org/chroot#Configuration

**Comment by onceme** [comment]
how to create a binary deb: http://www.tldp.org/HOWTO/html_single/Debian-Binary-Package-Building-HOWTO/

**Comment by onceme** [comment]
raspap-webgui
- SSID: bithollow-bh, pass: bithollow
- webgui user: bit, pass: hollow

**Comment by droneboost** [comment]
So we can test your rpi.img.xz now?

**Comment by onceme** [comment]
Yes, please try. I will close this issue after updated website for usage.

**Comment by onceme** [comment]
download page updated here: http://bithollow.github.io/downloads
