### ISSUE TITLE
[M3][High] 8 pwm RCInput bug fix

### ISSUE THREAD

**Issue by onceme** [bithollow/bitforge#61]
- Background
  ArduPilot RCInput_RPI 8 pwm input will crash in the latest ArduPilot code, the reason is related to BCM283x dma and pcm settings
- TODO
  - [x] debug and fix the crash in latest ArduPilot code
- Output
  - [x] good patch merged to upstream

**Comment by onceme** [comment]
related reports:
- https://github.com/ArduPilot/ardupilot/issues/3509
- https://github.com/ArduPilot/ardupilot/pull/3489
- https://github.com/ArduPilot/ardupilot/issues/3414

**Comment by onceme** [comment]
https://www.raspberrypi.org/documentation/hardware/raspberrypi/bcm2835/BCM2835-ARM-Peripherals.pdf

**Comment by onceme** [comment]
E.T.A 2017/1/26

**Comment by onceme** [comment]
E.T.A 2017/3/31, blocked by other tasks not in bithollow, I'm always trying to catch up.

**Comment by onceme** [comment]
E.T.A 2017/4/28.

**Comment by onceme** [comment]
Debugging this by print log is quite troublesome, debug with gdb could refer to this [gist](https://gist.github.com/onceme/e8de50f6b835e4868e90cee9d86b84a8).

With the setting in gist, I can debug from Host machine remotely to RPI

**Comment by onceme** [comment]
more information about gdb debug, could refer to the following:
- [Debugging with GDB: TUI](https://sourceware.org/gdb/current/onlinedocs/gdb/TUI-Overview.html#TUI-Overview)
- [Debugging with GDB: Remove Debugging](https://sourceware.org/gdb/current/onlinedocs/gdb/Remote-Debugging.html#Remote-Debugging)
- [gdb-multiarch](http://stackoverflow.com/questions/25143757/arm-linux-gnueabihf-gdb-versus-gdb-multiarch)

**Comment by onceme** [comment]
The screenshot while I'm debugging RCInput_RPI

![screenshot](https://cloud.githubusercontent.com/assets/5754278/25082359/e0b43308-2382-11e7-962f-4e3a2ee0a355.png)

**Comment by droneboost** [comment]
Looks good!

**Comment by onceme** [comment]
bcm283x clock source memo: https://raspberrypi.stackexchange.com/questions/1153/what-are-the-different-clock-sources-for-the-general-purpose-clocks

**Comment by droneboost** [comment]
any progress?

**Comment by onceme** [comment]
Solving PCM DREQ signal issue, just updated to today's latest upstream. The signal might be one of the cause of DMA deactivation. Simple words, not yet.

**Comment by onceme** [comment]
I believe the bug was fixed in here: https://github.com/bithollow/ardupilot/commit/cf7711f83d7189eb873afaf4f2a39354201429e9

#### Summary
- It was caused by the DMA chain transfer deactivation. Existing PCM or DMA settings are correct, but the memory pages used by DMA control block and circle buffer probably corrupted by something outside of RCInput_RPI, once the control block chain was corrupted, DMA_CONBLK_AD might be zero then cause DMA transfer to stop (according to page 38, 4 DMA Controller, BCM2835 datasheet).
- This issue was not caused by BH PWM support modifications, it was existing even on the latest upstream branches, just because the upstream code used many control block pages, the time of acquiring these pages incidentally avoided the memory corruption from outside RCInput_RPI.
- I didn't find out who/what of the outside factor caused it, but added logic whenever the DMA stopped, it will be restarted again. This is now working well in the aging test and PPM/PWM monkey test.
- In the meantime, the performance of RCInput_RPI is increased around 8 times, memory footprint reduced to about 8% compare to original, from 3680 KB to 272 KB.

**Comment by droneboost** [comment]
Great Job！ Would you PR to Ardupilot Upstream and  talk with them?

**Comment by onceme** [comment]
@droneboost I will do the following before launch PR

- pull Copter-3.5 from upstream to bithollow, then apply this patch as *bithollow release*
- create .deb binary and update to bithollow website download page based on *bithollow release*

Please feedback me once you got the .deb file

**Comment by droneboost** [comment]
OK, I See.

**Comment by onceme** [comment]
Default branch of https://github.com/bithollow/ardupilot is now Copter-3.5-BH-develop

**Comment by onceme** [comment]
@droneboost @muzi-15 
You can download latest deb from website, please feedback to me once you have time to do field test. Just let you know this version would be great:)

**Comment by onceme** [comment]
Upstream PR: https://github.com/ArduPilot/ardupilot/pull/6755

**Comment by droneboost** [comment]
Saw it, Great progress!

**Comment by onceme** [comment]
Upstream PR merger here: https://github.com/ArduPilot/ardupilot/pull/8967
