### ISSUE TITLE
[M3] software support power module on BH.

### ISSUE THREAD

**Issue by muzi-15** [bithollow/bitforge#64]
Background: Real-time battery voltage checking and notify.
TODO:   Modify software to support.
Output:  APM software

**Comment by muzi-15** [comment]
need about 2 days

**Comment by muzi-15** [comment]
Need add the bellow in the AP_BattMinor_Analog.h(3DR power module).
due to there is no actual power module, so use the sonar to simulate and result is ok.

define AP_BATT_VOLT_PIN 0
define AP_BATT_CURR_PIN 1
define AP_BATT_VOLTDIVIDER_DEFAULT 10.1f
define AP_BATT_CURR_AMP_PERVOLT_DEFAULT 17.0f

**Comment by onceme** [comment]
If we don't modify the code, can we enable power module by setting APM Planner?

**Comment by muzi-15** [comment]
eplease refer to the "power modules" webpage for the detailed informations.

**Comment by muzi-15** [comment]
has updated the power module page. so close it.
