### ISSUE TITLE
[M1][High][HW] Solder PCA9685 prototype on breadboard 

### ISSUE THREAD

**Issue by droneboost** [bithollow/bitforge#7]

**Comment by muzi-15** [comment]
the total cost this time is 110 + 14 + 23 = 147, the detailed information is as follows:
1. pca9685 chip x5  22X5
    http://detail.tmall.com/item.htm?id=41866364083&spm=a1z09.2.9.10.rCck0g&_u=g35sn0n834d&mt=
2. resistance 7X2
    http://detail.tmall.com/item.htm?  id=39813854420&spm=a1z09.2.9.27.rCck0g&_u=g35sn0nf703&mt=
3. convert board and bread board  23
    http://detail.tmall.com/item.htm?id=25072296568&spm=a1z09.2.9.44.rCck0g&_u=g35sn0n791e&mt=
   http://detail.tmall.com/item.htm?id=25282796860&spm=a1z09.2.9.64.rCck0g&_u=g35sn0n12aa&mt=

**Comment by onceme** [comment]
How much should I pay you? 147/3=49?

**Comment by droneboost** [comment]
I also want to know.

**Comment by muzi-15** [comment]
till now the PCA9685 prototype can work

**Comment by onceme** [comment]
@muzi-15 consider to close this issue

**Comment by droneboost** [comment]
Since BH first edition has come out, I close this issue.
